
animations = true;
animation-stiffness = 150;
animation-dampening = 20;
animation-clamping = false;
animation-mass = 0.8;

animation-for-open-window = "zoom";
animation-for-unmap-window = "zoom";

animation-exclude = [
    "class_g = 'Polybar'",
    "window_type = 'dock'"
];


#################################
#           Corners             #
#################################
# We want the bar to be rounded to match the 'radius = 4' in Polybar
corner-radius = 8;
rounded-corners-exclude = [
  "window_type = 'desktop'"
];

#################################
#             Blur              #
#################################
blur: {
  method = "dual_kawase";
  strength = 5;      # Higher strength = More "Frosted"
  background = true;  # REQUIRED for glass effect
  background-frame = false;
  background-fixed = false;
}

# Ensure Polybar isn't being ignored by the blur engine
blur-background-exclude = [
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];

#################################
#       Backend & Performance   #
#################################
backend = "glx";
# Keeping your performance tweaks
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
use-damage = true;
vsync = true;

opacity-rule = [
  "90:class_g = 'Alacritty' && !focused",
  "100:class_g = 'Alacritty' && focused"
];

fading = true;
fade-in-step = 0.3;
fade-out-step = 0.3;
fade-delta = 12;

blur-background-exclude = [
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];
